---
javascripts:
- base:
  - jquery
  - jquery.livequery
  - fonts/cufon-yui
  - fonts/Museo_Sans
  - fonts/Museo_Slab
  - jquery-ui-1.8.5.custom.min
  - jquery.scrollTo-min
  - jquery.url
  - application
- openlayer:
  - OpenLayers
  - cloudmade
  - SiteMarker
  - jquery
  - jquery.stylish-select
  - jquery-ui-1.8.5.custom.min
- explore:
  - explore
stylesheets:
- base:
  - layout
  - jquery-ui-1.8.5.custom
