development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: ushelf_development
  username: postgres
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: ushelf_test
  username: postgres
  password:
